[package]
name = "wasm-sapling"
version = "0.0.1"
authors = ["Papers.ch <contact@papers.ch>"]
edition = "2018"

[lib]
name = "wasm_sapling"
crate-type = ["cdylib", "rlib"]

[package.metadata.wasm-pack.profile.release]
wasm-opt = ["-Oz", "--enable-mutable-globals"]

[dependencies]
wasm-bindgen = "0.2.67"
regex = "1.3.9"
zcash_primitives = "0.2"

[dev-dependencies]
tiny-bip39 = "0.7.3"